import React from 'react';
import TopNav from '../components/TopNav.tsx';
import BottomNav from '../components/BottomNav.tsx';
import StatCard from '../components/StatCard.tsx';
import ChartCard from '../components/ChartCard.tsx';

function AdminReportsPage() {
  const navItems = [
    { path: '/admin', label: 'Dashboard' },
    { path: '/admin/users', label: 'Users' },
    { path: '/admin/security', label: 'Security' },
    { path: '/admin/reports', label: 'Reports', active: true }
  ];

  return (
    <div className="app-container mobile-only">
      <TopNav showBackButton={true} />
      
      <div className="main-content">
        <div className="page-header">
          <div className="page-title">Reports & Analytics</div>
          <div className="page-subtitle">Business intelligence and insights</div>
        </div>
        
        <div className="dashboard-grid">
          <StatCard value="R840k" label="Monthly Revenue" />
          <StatCard value="88%" label="Occupancy Rate" />
          <StatCard value="95%" label="Collection Rate" />
          <StatCard value="24" label="Active Reports" />
        </div>

        <ChartCard title="Financial Overview">
          <div className="chart-placeholder">
            Chart.js Financial Analytics
          </div>
        </ChartCard>

        <div className="data-table">
          <div className="table-header">
            <div className="table-title">Available Reports</div>
          </div>
          
          <div className="list-item">
            <div className="item-info">
              <h4>Monthly Financial Report</h4>
              <p>Revenue, expenses, and profit analysis</p>
            </div>
            <span className="status-badge status-ready">Ready</span>
          </div>
          
          <div className="list-item">
            <div className="item-info">
              <h4>Property Performance Report</h4>
              <p>Occupancy rates and property metrics</p>
            </div>
            <span className="status-badge status-ready">Ready</span>
          </div>
          
          <div className="list-item">
            <div className="item-info">
              <h4>Maintenance Summary Report</h4>
              <p>Maintenance costs and resolution times</p>
            </div>
            <span className="status-badge status-processing">Processing</span>
          </div>
        </div>

        <div className="data-table">
          <div className="table-header">
            <div className="table-title">Report Generation</div>
          </div>
          
          <div className="form-group">
            <label className="form-label">Report Type</label>
            <select className="form-select">
              <option>Financial Report</option>
              <option>Occupancy Report</option>
              <option>Maintenance Report</option>
              <option>Performance Report</option>
              <option>Custom Report</option>
            </select>
          </div>
          
          <div className="form-row">
            <div className="form-group">
              <label className="form-label">From Date</label>
              <input type="date" className="form-input" />
            </div>
            <div className="form-group">
              <label className="form-label">To Date</label>
              <input type="date" className="form-input" />
            </div>
          </div>
          
          <button className="btn-primary btn-block">Generate Report</button>
        </div>

        <div className="data-table">
          <div className="table-header">
            <div className="table-title">Recent Report Activity</div>
          </div>
          <div className="list-item">
            <div className="item-info">
              <h4>Monthly Financial Report generated</h4>
              <p>2 hours ago - Generated by Sarah Johnson</p>
            </div>
          </div>
          <div className="list-item">
            <div className="item-info">
              <h4>Property Performance Report downloaded</h4>
              <p>5 hours ago - Downloaded by Michael Chen</p>
            </div>
          </div>
          <div className="list-item">
            <div className="item-info">
              <h4>Custom Occupancy Report generated</h4>
              <p>1 day ago - Generated by Patricia Williams</p>
            </div>
          </div>
        </div>
      </div>
      
      <BottomNav items={navItems} responsive={false} />
    </div>
  );
}

export default AdminReportsPage;
